--[[
	
				MTA:BG
			MTA Battlegrounds
	Developed By: L, CiBeR, neves768, 1BOY

]]--

playerDataTable = {
{"skin",0},
{"Kills",0},
{"InventoryCapacity",10},
{"UsedCapacity",0},
{"health",100},
{"armor",0},
{"currentweapon_1",false},
{"currentweapon_2",false},
{"currentweapon_3",false},
{"headshots",0},
}

playerInventoryTable = {
{"M1911",0},
{"Revolver",0},
{"Bizon PP-19 SD",0},
{"M9",0},
{"Makarov SD",0},
{"PDW",0},
{"MP5A5",0},
{"AK-74",0},
{"AKM",0},
{"Sa58V CCO",0},
{"FN FAL",0},
{"M24",0},
{"DMR",0},
{"G36C",0},
{"M16A2",0},
{"M4A1",0},
{"CZ 550",0},
{"SVD Dragunov",0},
{"Mosin-Nagant",0},
{"Winchester 1866",0},
{"Double-barreled Shotgun",0},
{"M1014",0},
{"Compound Crossbow",0},
{"Baseball Bat",0},
{"Axe",0},
{"Parachute",0},
{"Grenade",0},
{"Hunting Knife",0},
{"Binoculars",0},
{"Range Finder",0},
{"Shovel",0},
{"11.43x23mm Cartridge",0},
{"9x18mm Cartridge",0},
{"9x19mm Cartridge",0},
{".303 British Cartridge",0},
{"7.62x39mm Cartridge",0},
{"5.56x45mm Cartridge",0},
{"7.62x54mm Cartridge",0},
{"1866 Slug",0},
{"12 Gauge Pellet",0},
{"Bolt",0},
{"Energy Drink",0},
{"Bandage",5},
{"Full Gas Canister",0},
{"Painkiller",0},
{"IR Goggles",0},
{"NV Goggles",0},
{"Camouflage Clothing",0},
{"Civilian Clothing",0},
{"Survivor Clothing",0},
{"Survivor Clothing (Female)",0},
{"Civilian Clothing (Female)",0},
{"Ghillie Suit",0},
{"Assault Pack (ACU)",0},
{"ALICE Pack",0},
{"British Assault Pack",0},
{"Czech Vest Pouch",0},
{"Backpack (Coyote)",0},
{"Czech Backpack",0},
{"Survival ACU",0},
}