local langFilePath = "lang/cLanguageStrings.lua"
local langFile

local function open()
	langFile = File.new(langFilePath)
end

local function close()
	langFile:close()
	langFile = nil
end

local function writeHeader()
	langFile:write("--Language table\n")
	langFile:write("Language = {")
end

local function writeFooter()
	langFile:write("\n")
	langFile:write("}\n\n")
	langFile:write("--This script was generated by a script.\n")
end

local function writeLanguageEntries()
	for langNumber, language in ipairs(LanguageParser.availableLanguages) do
		langFile:write("\n\t")
		langFile:write(language)
		langFile:write(" = {")
		for number, name in ipairs(LanguageParser.stringNames) do
			langFile:write("\n\t\t")
			langFile:write(name)
			langFile:write(" = ")
			langFile:write("\"")
			if LanguageParser.stringsOfALanguage[language][number] then
				langFile:write(LanguageParser.stringsOfALanguage[language][number])
			elseif LanguageParser.stringsOfALanguage["en"][number] then
				langFile:write(LanguageParser.stringsOfALanguage["en"][number])
			else
				langFile:write(name)
			end
			langFile:write("\"")
			if number < #LanguageParser.stringNames then
				langFile:write(",")
			end
		end
		langFile:write("\n\t}")
		if langNumber < #LanguageParser.availableLanguages then
			langFile:write(",")
		end
	end
end

local function writeAvailableLanguages()
	langFile:write("\n\n\tavailable = {")
	for langNumber, language in ipairs(LanguageParser.availableLanguages) do
		langFile:write(" \"")
		langFile:write(language)
		langFile:write("\"")
		if langNumber < #LanguageParser.availableLanguages then
			langFile:write(",")
		end
	end
	langFile:write(" },\n")
end

local function writeAvailableLanguageNames()
	langFile:write("\tavailableNames = {")
	for langNumber, language in ipairs(LanguageParser.availableLanguageNames) do
		langFile:write(" \"")
		langFile:write(language)
		langFile:write("\"")
		if langNumber < #LanguageParser.availableLanguageNames then
			langFile:write(",")
		end
	end
	langFile:write(" },\n")
end

local function write()
	writeHeader()
	writeAvailableLanguages()
	writeAvailableLanguageNames()
	writeLanguageEntries()
	writeFooter()
end

function LanguageParser.writeLuaFile()
	open()
	write()
	close()
end
